name: base36
channels:
- conda-forge
- defaults
dependencies:
- python=3.6
- cached-property
- click
- cython
- dask
- distributed
- gensim
- h5py
- hdfs3
- ipdb
- ipykernel
- ipython
- ipyvolume
- ipywidgets
- joblib
- jupyter
#- jupyter_contrib_nbextensions
- matplotlib
- nbconvert
- nbformat
- networkx
- nltk
- nodejs
- notebook
- numba
- numpy
- pandas
- pip
- progressbar2
- pydot
- pytest
- scikit-learn
- scipy
- seaborn
- spacy
- statsmodels
- tqdm
- ujson
- pip:
  - jupyterlab
  - jupyterlab-discovery
  - jupyterlab-geojson
  - jupyterlab-widgets
  - keras-tqdm
  - nbdime
  - setuptools-rust
  - snakeviz
  - vprof
  - "https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.10.1-cp36-cp36m-linux_x86_64.whl"
  #- "https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.10.1-cp36-cp36m-linux_x86_64.whl"
  - "git+https://github.com/ixxi-dante/keras@b50534bd55151c72782ecc630e21bb2e4d9a68d7#egg=keras"
  - "git+https://github.com/ixxi-dante/jwalk@03aac5dc0bd6d2dad496a00e4d0dc127ef2c87c0#egg=jwalk"
  - "--editable=."

