name: base36
channels:
- defaults
dependencies:
- python=3.6
- cached-property
- click
- cython
- dask
- distributed
- gensim
- h5py
- ipykernel
- ipython
- ipywidgets
- joblib
- jupyter
- jupyterlab
- matplotlib
- nbconvert
- nbformat
- networkx
- nltk
- nodejs
- numba
- numpy
- pandas
- pip
- progressbar2
- pyarrow
- pydot
- pympler
- pytest
- scikit-learn
- scipy
- seaborn
- snakeviz
- spacy
- statsmodels
# CPU tensorflow
- tensorflow
# GPU tensorflow
#- tensorflow-gpu
- tqdm
- ujson
- pip:
  - ipdb
  - ipyvolume
  - jupyter_contrib_nbextensions
  - keras-tqdm
  - nbdime
  - setuptools-rust
  - vprof
  - "git+https://github.com/ixxi-dante/keras@b50534bd55151c72782ecc630e21bb2e4d9a68d7#egg=keras"
  - "git+https://github.com/ixxi-dante/jwalk@03aac5dc0bd6d2dad496a00e4d0dc127ef2c87c0#egg=jwalk"
  - "--editable=."

