[package]
name = "nw2vec-rust"
version = "0.1.0"
authors = ["Sébastien Lerique <sl@mehho.net>"]

[lib]
name = "_nw2vec_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.2", features = ["extension-module"] }
rayon = "1.0"
regex = "1.0"
